const programmarTeam = [
  {
    id: 121,
    name: "mosiur rahnam",
    company: "coders foundation",
    country: "Bangladesh",
    salary: 2000,
    age: 28,
    position: "CEO",
    img: "2wCEAAoHCBYVFRgWFhYYGRgaGhocGBkaGhwYGhoYGBgaGRoYGBocIS4lHB4rHxgZJjgmKy8xNTU1Gic7QDszPy40NTEBDAwMEA8QGhISHjQkISQ0NDQ0NDQxNDQ0NDQ0NDQ0NDE0NDQ0NDQ0NDQ0NDQ0NDQxPz80PzE0NDQ0MTE0MTExMf",
  },
  {
    id: 122,
    name: "rasel ahmod",
    company: "rr foundetion",
    country: "Bangladesh",
    salary: 2500,
    age: 32,
    position: "CEO",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSnZKI6W1AG7eRF32SJjha9pvFDCeC-p4bGA&usqp=CAU",
  },
  {
    id: 123,
    name: "amdad vai",
    company: "programming hero",
    country: "Bangladesh",
    salary: 2500,
    age: 27,
    position: "Assistant Manager",
    img: "https://web.programming-hero.com/public/1625574121230.png",
  },
];
